const mongoose = require("mongoose");

const schema = new mongoose.Schema(
    {
        resume: { type: String },
        job_code: { type: String },
        job_position: { type: String },
        job_type: { type: String },
        profile_image: { type: String },
        title: { type: String },
        firstname: { type: String },
        lastname: { type: String },
        nickname: { type: String },
        age: { type: String },
        gender: { type: String },
        phone: { type: String },
        telephone: { type: String },
        address: { type: String },
        email: { type: String },
        rate_min: { type: String },
        rate_max: { type: String },
        personal_detail: { type: String },
        en_skill: { type: String },
        en_skill_file: { type: String },
        jp_skill: { type: String },
        jp_skill_file: { type: String },
        ch_skill: { type: String },
        ch_skill_file: { type: String },
        kr_skill: { type: String },
        kr_skill_file: { type: String },
        other_skill: { type: String },
        company_name: { type: String },
        start_month: { type: String },
        start_year: { type: String },
        end_month: { type: String },
        end_year: { type: String },
        detail: { type: String }
    },
    { timestamps: true }
);

// Custom JSON Response
schema.methods.toJSON = function () {
    return {
        id: this._id,
        resume: this.resume,
        job_code: this.job_code,
        job_position: this.job_position,
        job_type: this.job_type,
        profile_image: this.profile_image,
        title: this.title,
        firstname: this.firstname,
        lastname: this.lastname,
        nickname: this.nickname,
        age: this.age,
        gender: this.gender,
        phone: this.phone,
        telephone: this.telephone,
        address: this.address,
        email: this.email,
        rate_min: this.rate_min,
        rate_max: this.rate_max,
        personal_detail: this.personal_detail,
        en_skill: this.en_skill,
        en_skill_file: this.en_skill_file,
        jp_skill: this.jp_skill,
        jp_skill_file: this.jp_skill_file,
        ch_skill: this.ch_skill,
        ch_skill_file: this.ch_skill_file,
        kr_skill: this.kr_skill,
        kr_skill_file: this.kr_skill_file,
        other_skill: this.other_skill,
        company_name: this.company_name,
        start_month: this.start_month,
        start_year: this.start_year,
        end_month: this.end_month,
        end_year: this.end_year,
        detail: this.detail,
        createdAt: this.createdAt,
        updatedAt: this.updatedAt,
    };
};

module.exports = mongoose.model("tb_jobapply", schema);
